---
title: "LDA Trials"
author: "Daniel Wang"
date: '2022-04-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(curl)
library(jsonlite)
library(rvest)
library(tm)
library(tidytext)
library(topicmodels)
```

Import Godfather movie reviews

```{r}
url <- 'https://api.nytimes.com/svc/movies/v2/reviews/search.json?opening-date=2000-01-01:2020-01-01&api-key=52utY7TeqStbbVwadabbLam6qUdac7d5'
url <- 'https://api.nytimes.com/svc/movies/v2/reviews/search.json?query=godfather&api-key=52utY7TeqStbbVwadabbLam6qUdac7d5'
json_result <- url %>% curl() %>% readLines() %>% fromJSON()
json_result
```

```{r}
url_html <- 'https://www.nytimes.com/2019/06/06/movies/the-black-godfather-review.html'
url_html %>% read_html() %>% html_nodes("section") %>% html_nodes("p") %>% html_text2()
```

Create a function which extracts the text from each of the movie reviews using html web scraping

```{r}
extract_text <- function(json_result){
  reviews <- json_result$result %>% 
    dplyr::select(c('display_title','headline','link')) %>% 
    mutate(url = link$url) %>%
    select(-link)
  review_text <-tibble(headline = '',text='')
  for(i in 1:nrow(reviews)){
    url_html <- reviews[i,3]
    review_text <- review_text %>% add_row(headline = reviews[i,2], text = url_html %>% read_html() %>% html_nodes("section") %>% html_nodes("p") %>% html_text2())
  }
  review_text <- review_text %>% group_by(headline) %>% summarise(text = paste(text,collapse = " "))
  return(review_text)
}
```

Clean the movie review text

```{r}
review_text <- extract_text(json_result)
review_text <- review_text %>% mutate(
  clean_text = tolower(text),
  clean_text = str_replace_all(clean_text,"[['`’]]", ""), 
  clean_text = str_replace_all(clean_text,"[[:punct:]]", " "),
  clean_text = str_replace_all(clean_text,'[[:digit:]]+', " "),
  clean_text = str_replace_all(clean_text,"[[:space:]]+", " "),
  clean_text = removeWords(clean_text,stopwords("english")),
  clean_text = trimws(clean_text)) 

```

Turn the movie review text into a DTM (Document Term Matrix) for text mining.

```{r}
dtm_reviews <- tm::DocumentTermMatrix(tm::VCorpus(tm::VectorSource(review_text$clean_text)),control=list(wordLengths=c(1,Inf)))
dtm_reviews
```

```{r}
raw.sum=apply(dtm_reviews,1,FUN=sum)
dtm_reviews=dtm_reviews[raw.sum!=0,]
reviews_lda <- LDA(dtm_reviews, k = 2)
reviews_topics <- tidy(reviews_lda)
reviews_topics
```

```{r}
reviews_lda %>% tidy(matrix="gamma") %>%
  group_by(document) %>%
  top_n(1)
```


```{r}
reviews_topics %>% filter(topic==1) %>% 
  mutate(beta_rank = min_rank(desc(beta))) %>% 
  filter(beta_rank <= 10) %>% 
  arrange(beta_rank) %>%
  mutate(term = reorder(term, beta)) %>% 
  ggplot(aes(beta, term)) + 
  geom_col(show.legend = FALSE)
```