---
title: "Sentiment Analysis Trials"
author: "Pratiksha Ajit Sharma"
date: "24/04/2022"
output: html_document
---

```{r}
library(tidyverse)
library(httr)
library(curl)
library(jsonlite)
library(rvest)
library(stringr)
library(tidytext) 
library(textdata)
```


Import Godfather movie reviews

```{r}
url <- 'https://api.nytimes.com/svc/movies/v2/reviews/search.json?query=godfather&api-key=ltnSuqlZoDGg6Td519vELgT8Fncs2Bq7'
json_result <- url %>% curl() %>% readLines() %>% fromJSON()
json_result
```

```{r}
url_html <- 'https://www.nytimes.com/2019/06/06/movies/the-black-godfather-review.html'
url_html %>% read_html() %>% html_nodes("section") %>% html_nodes("p") %>% html_text2()
```

Create a function which extracts the text from each of the movie reviews using html web scraping

```{r}
extract_text <- function(json_result){
  reviews <- json_result$result %>% 
    dplyr::select(c('display_title','headline','link')) %>% 
    mutate(url = link$url) %>%
    select(-link)
  review_text <-tibble(headline = '',text='')
  for(i in 1:nrow(reviews)){
    url_html <- reviews[i,3]
    review_text <- review_text %>% add_row(headline = reviews[i,2], text = url_html %>% read_html() %>% html_nodes("section") %>% html_nodes("p") %>% html_text2())
  }
  review_text <- review_text %>% group_by(headline) %>% summarise(text = paste(text,collapse = " "))
  return(review_text)
}
```

Clean the movie review text

```{r}
review_text <- extract_text(json_result)
review_text <- review_text %>% mutate(
  clean_text = tolower(text),
  clean_text = str_replace_all(clean_text,"['`]", ""), 
  clean_text = str_replace_all(clean_text,"[[:punct:]]", " "),
  clean_text = str_replace_all(clean_text,'[[:digit:]]+', " "),
  clean_text = str_replace_all(clean_text,"[[:space:]]+", " "),
  clean_text = trimws(clean_text)) 
```

```{r}
tidy_text = review_text %>% group_by(headline) %>% unnest_tokens(word, clean_text)
```


Separating words for Sentiment Analysis

```{r}
nrc_joy <- get_sentiments("nrc") %>%  filter(sentiment == "joy")
nrc_positive <- get_sentiments("nrc") %>%  filter(sentiment == "positive")
nrc_negative <- get_sentiments("nrc") %>%  filter(sentiment == "negative")
nrc_anger <- get_sentiments("nrc") %>%  filter(sentiment == "anger")
nrc_anticipation <- get_sentiments("nrc") %>%  filter(sentiment == "anticipation")
nrc_disgust <- get_sentiments("nrc") %>%  filter(sentiment == "disgust")
nrc_fear <- get_sentiments("nrc") %>%  filter(sentiment == "fear")
nrc_surprise <- get_sentiments("nrc") %>%  filter(sentiment == "surprise")
nrc_sadness <- get_sentiments("nrc") %>%  filter(sentiment == "sadness")
nrc_trust <- get_sentiments("nrc") %>%  filter(sentiment == "trust")
```

Merging sentiments from reviews and our lexicons

```{r}
movie_reviews_joy = tidy_text %>% inner_join(nrc_joy) %>%count(word, sort = TRUE)
movie_reviews_positive = tidy_text %>% inner_join(nrc_positive) %>%count(word, sort = TRUE)
movie_reviews_negative = tidy_text %>% inner_join(nrc_negative) %>%count(word, sort = TRUE)
movie_reviews_anger = tidy_text %>% inner_join(nrc_anger) %>%count(word, sort = TRUE)
movie_reviews_anticipation = tidy_text %>% inner_join(nrc_anticipation) %>%count(word, sort = TRUE)
movie_reviews_disgust = tidy_text %>% inner_join(nrc_disgust) %>%count(word, sort = TRUE)
movie_reviews_fear = tidy_text %>% inner_join(nrc_fear) %>%count(word, sort = TRUE)
movie_reviews_surprise = tidy_text %>% inner_join(nrc_surprise) %>%count(word, sort = TRUE)
movie_reviews_sadness = tidy_text %>% inner_join(nrc_sadness) %>%count(word, sort = TRUE)
movie_reviews_trust = tidy_text %>% inner_join(nrc_trust) %>%count(word, sort = TRUE)
```

```{r}
movie_reviews_anger
```

```{r}
bing_positive <- get_sentiments("bing") %>%  filter(sentiment == "positive")
bing_negative <- get_sentiments("bing") %>%  filter(sentiment == "negative")
```

```{r}
movie_reviews_positive_bing = tidy_text %>% inner_join(bing_positive) %>%count(word, sort = TRUE)
movie_reviews_negative_bing = tidy_text %>% inner_join(bing_negative) %>%count(word, sort = TRUE)
```

```{r}
head(movie_reviews_negative_bing)
```


```{r}
head(movie_reviews_positive_bing)
```

```{r}
movie_reviews_afinn <- tidy_text %>% inner_join(get_sentiments("afinn"))
head(movie_reviews_afinn)
```

```{r}
aggregate(x = movie_reviews_afinn$value, by = list(movie_reviews_afinn$headline),FUN = sum) %>% arrange(x)
```

Most Popular API

```{r}
url2 <- 'https://api.nytimes.com/svc/mostpopular/v2/viewed/1.json?api-key=ltnSuqlZoDGg6Td519vELgT8Fncs2Bq7'
json_result2 <- url2 %>% curl() %>% readLines() %>% fromJSON()
json_result2
```

